/*
 * Cc2Text.c — mod target definitions for LXR-02.
 * Ported from original LXR AVR Cc2Text.c by Julian Schmidt / AS.
 * PROGMEM stripped. Direct array access.
 */

/*
 *  Modified on: 17.05.2026
 * ------------------------------------------------------------------------------------------------------------------------
 *  Modifications Copyright 2026 Brendan Clarke
 *  brendanpaulclarke@gmail.com
 *  https://www.brendanclarke.com
 * ------------------------------------------------------------------------------------------------------------------------
 *  The modifications to this file are part of the LXR02 Open-Source software.
 *  The same license and restrictions on use for the LXR software apply.
 * ------------------------------------------------------------------------------------------------------------------------
 */

#include "CcNr2Text.h"
#include "menu.h"
#include <stdint.h>

const ModTarg modTargets[] = {
{TEXT_EMPTY,PAR_NONE},
{TEXT_SAMPLE_RATE,PAR_VOICE_DECIMATION_ALL},
/* Voice 1 */
{TEXT_COARSE,PAR_COARSE1},{TEXT_FINE,PAR_FINE1},{TEXT_WAVEFORM,PAR_OSC_WAVE_DRUM1},
{TEXT_ATTACK,PAR_VELOA1},{TEXT_DECAY,PAR_VELOD1},{TEXT_EG_SLOPE,PAR_VOL_SLOPE1},
{TEXT_PITCH_DECAY,PAR_MOD_EG1},{TEXT_EG_SLOPE,PAR_PITCH_SLOPE1},{TEXT_MOD_AMOUNT,PAR_MODAMNT1},
{TEXT_VEL_DEST,PAR_VEL_DEST_1},{TEXT_VEL_AMT,PAR_VELO_MOD_AMT_1},{TEXT_VEL_MOD_VOL,PAR_VOLUME_MOD_ON_OFF1},
{TEXT_FM_AMOUNT,PAR_FMAMNT1},{TEXT_FM_FREQ,PAR_FM_FREQ1},{TEXT_WAVEFORM,PAR_MOD_WAVE_DRUM1},{TEXT_MODE,PAR_MIX_MOD_1},
{TEXT_TRANSIENT_WAVE,PAR_TRANS1_WAVE},{TEXT_TRANSIENT_VOLUME,PAR_TRANS1_VOL},{TEXT_TRANSIENT_FREQ,PAR_TRANS1_FREQ},
{TEXT_FILTER_F,PAR_FILTER_FREQ_1},{TEXT_FILTER_RESO,PAR_RESO_1},{TEXT_FILTER_TYPE,PAR_FILTER_TYPE_1},{TEXT_FILTER_DRIVE,PAR_FILTER_DRIVE_1},
{TEXT_FREQ_LFO,PAR_FREQ_LFO1},{TEXT_SYNC_LFO,PAR_SYNC_LFO1},{TEXT_MOD_LFO,PAR_AMOUNT_LFO1},{TEXT_WAVE_LFO,PAR_WAVE_LFO1},
{TEXT_RETRIGGER_LFO,PAR_RETRIGGER_LFO1},{TEXT_OFFSET_LFO,PAR_OFFSET_LFO1},
{TEXT_VOLUME,PAR_VOL1},{TEXT_PAN,PAR_PAN1},{TEXT_SAMPLE_RATE,PAR_VOICE_DECIMATION1},{TEXT_DRIVE,PAR_DRIVE1},{TEXT_NOTE,PAR_MIDI_NOTE1},
/* Voice 2 */
{TEXT_COARSE,PAR_COARSE2},{TEXT_FINE,PAR_FINE2},{TEXT_WAVEFORM,PAR_OSC_WAVE_DRUM2},
{TEXT_ATTACK,PAR_VELOA2},{TEXT_DECAY,PAR_VELOD2},{TEXT_EG_SLOPE,PAR_VOL_SLOPE2},
{TEXT_PITCH_DECAY,PAR_MOD_EG2},{TEXT_EG_SLOPE,PAR_PITCH_SLOPE2},{TEXT_MOD_AMOUNT,PAR_MODAMNT2},
{TEXT_VEL_DEST,PAR_VEL_DEST_2},{TEXT_VEL_AMT,PAR_VELO_MOD_AMT_2},{TEXT_VEL_MOD_VOL,PAR_VOLUME_MOD_ON_OFF2},
{TEXT_FM_AMOUNT,PAR_FMAMNT2},{TEXT_FM_FREQ,PAR_FM_FREQ2},{TEXT_WAVEFORM,PAR_MOD_WAVE_DRUM2},{TEXT_MODE,PAR_MIX_MOD_2},
{TEXT_TRANSIENT_WAVE,PAR_TRANS2_WAVE},{TEXT_TRANSIENT_VOLUME,PAR_TRANS2_VOL},{TEXT_TRANSIENT_FREQ,PAR_TRANS2_FREQ},
{TEXT_FILTER_F,PAR_FILTER_FREQ_2},{TEXT_FILTER_RESO,PAR_RESO_2},{TEXT_FILTER_TYPE,PAR_FILTER_TYPE_2},{TEXT_FILTER_DRIVE,PAR_FILTER_DRIVE_2},
{TEXT_FREQ_LFO,PAR_FREQ_LFO2},{TEXT_SYNC_LFO,PAR_SYNC_LFO2},{TEXT_MOD_LFO,PAR_AMOUNT_LFO2},{TEXT_WAVE_LFO,PAR_WAVE_LFO2},
{TEXT_RETRIGGER_LFO,PAR_RETRIGGER_LFO2},{TEXT_OFFSET_LFO,PAR_OFFSET_LFO2},
{TEXT_VOLUME,PAR_VOL2},{TEXT_PAN,PAR_PAN2},{TEXT_SAMPLE_RATE,PAR_VOICE_DECIMATION2},{TEXT_DRIVE,PAR_DRIVE2},{TEXT_NOTE,PAR_MIDI_NOTE2},
/* Voice 3 */
{TEXT_COARSE,PAR_COARSE3},{TEXT_FINE,PAR_FINE3},{TEXT_WAVEFORM,PAR_OSC_WAVE_DRUM3},
{TEXT_ATTACK,PAR_VELOA3},{TEXT_DECAY,PAR_VELOD3},{TEXT_EG_SLOPE,PAR_VOL_SLOPE3},
{TEXT_PITCH_DECAY,PAR_MOD_EG3},{TEXT_EG_SLOPE,PAR_PITCH_SLOPE3},{TEXT_MOD_AMOUNT,PAR_MODAMNT3},
{TEXT_VEL_DEST,PAR_VEL_DEST_3},{TEXT_VEL_AMT,PAR_VELO_MOD_AMT_3},{TEXT_VEL_MOD_VOL,PAR_VOLUME_MOD_ON_OFF3},
{TEXT_FM_AMOUNT,PAR_FMAMNT3},{TEXT_FM_FREQ,PAR_FM_FREQ3},{TEXT_WAVEFORM,PAR_MOD_WAVE_DRUM3},{TEXT_MODE,PAR_MIX_MOD_3},
{TEXT_TRANSIENT_WAVE,PAR_TRANS3_WAVE},{TEXT_TRANSIENT_VOLUME,PAR_TRANS3_VOL},{TEXT_TRANSIENT_FREQ,PAR_TRANS3_FREQ},
{TEXT_FILTER_F,PAR_FILTER_FREQ_3},{TEXT_FILTER_RESO,PAR_RESO_3},{TEXT_FILTER_TYPE,PAR_FILTER_TYPE_3},{TEXT_FILTER_DRIVE,PAR_FILTER_DRIVE_3},
{TEXT_FREQ_LFO,PAR_FREQ_LFO3},{TEXT_SYNC_LFO,PAR_SYNC_LFO3},{TEXT_MOD_LFO,PAR_AMOUNT_LFO3},{TEXT_WAVE_LFO,PAR_WAVE_LFO3},
{TEXT_RETRIGGER_LFO,PAR_RETRIGGER_LFO3},{TEXT_OFFSET_LFO,PAR_OFFSET_LFO3},
{TEXT_VOLUME,PAR_VOL3},{TEXT_PAN,PAR_PAN3},{TEXT_SAMPLE_RATE,PAR_VOICE_DECIMATION3},{TEXT_DRIVE,PAR_DRIVE3},{TEXT_NOTE,PAR_MIDI_NOTE3},
/* Voice 4 (snare) */
{TEXT_COARSE,PAR_COARSE4},{TEXT_FINE,PAR_FINE4},{TEXT_NOISE,PAR_NOISE_FREQ1},{TEXT_MIX,PAR_MIX1},{TEXT_WAVEFORM,PAR_OSC_WAVE_SNARE},
{TEXT_ATTACK,PAR_VELOA4},{TEXT_DECAY,PAR_VELOD4},{TEXT_REPEAT,PAR_REPEAT4},{TEXT_EG_SLOPE,PAR_VOL_SLOPE4},
{TEXT_PITCH_DECAY,PAR_MOD_EG4},{TEXT_EG_SLOPE,PAR_PITCH_SLOPE4},{TEXT_MOD_AMOUNT,PAR_MODAMNT4},
{TEXT_VEL_DEST,PAR_VEL_DEST_4},{TEXT_VEL_AMT,PAR_VELO_MOD_AMT_4},{TEXT_VEL_MOD_VOL,PAR_VOLUME_MOD_ON_OFF4},
{TEXT_TRANSIENT_WAVE,PAR_TRANS4_WAVE},{TEXT_TRANSIENT_VOLUME,PAR_TRANS4_VOL},{TEXT_TRANSIENT_FREQ,PAR_TRANS4_FREQ},
{TEXT_FILTER_F,PAR_FILTER_FREQ_4},{TEXT_FILTER_RESO,PAR_RESO_4},{TEXT_FILTER_TYPE,PAR_FILTER_TYPE_4},{TEXT_FILTER_DRIVE,PAR_FILTER_DRIVE_4},
{TEXT_FREQ_LFO,PAR_FREQ_LFO4},{TEXT_SYNC_LFO,PAR_SYNC_LFO4},{TEXT_MOD_LFO,PAR_AMOUNT_LFO4},{TEXT_WAVE_LFO,PAR_WAVE_LFO4},
{TEXT_RETRIGGER_LFO,PAR_RETRIGGER_LFO4},{TEXT_OFFSET_LFO,PAR_OFFSET_LFO4},
{TEXT_VOLUME,PAR_VOL4},{TEXT_PAN,PAR_PAN4},{TEXT_SAMPLE_RATE,PAR_VOICE_DECIMATION4},{TEXT_DRIVE,PAR_SNARE_DISTORTION},{TEXT_NOTE,PAR_MIDI_NOTE4},
/* Voice 5 (cymbal) */
{TEXT_COARSE,PAR_COARSE5},{TEXT_FINE,PAR_FINE5},{TEXT_WAVEFORM,PAR_WAVE1_CYM},
{TEXT_ATTACK,PAR_VELOA5},{TEXT_DECAY,PAR_VELOD5},{TEXT_REPEAT,PAR_REPEAT5},{TEXT_EG_SLOPE,PAR_VOL_SLOPE5},
{TEXT_VEL_DEST,PAR_VEL_DEST_5},{TEXT_VEL_AMT,PAR_VELO_MOD_AMT_5},{TEXT_VEL_MOD_VOL,PAR_VOLUME_MOD_ON_OFF5},
{TEXT_MOD_OSC1_FREQ,PAR_MOD_OSC_F1_CYM},{TEXT_MOD_OSC2_FREQ,PAR_MOD_OSC_F2_CYM},
{TEXT_MOD_OSC1_GAIN,PAR_MOD_OSC_GAIN1_CYM},{TEXT_MOD_OSC2_GAIN,PAR_MOD_OSC_GAIN2_CYM},
{TEXT_WAVEFORM,PAR_WAVE2_CYM},{TEXT_WAVEFORM,PAR_WAVE3_CYM},
{TEXT_TRANSIENT_WAVE,PAR_TRANS5_WAVE},{TEXT_TRANSIENT_VOLUME,PAR_TRANS5_VOL},{TEXT_TRANSIENT_FREQ,PAR_TRANS5_FREQ},
{TEXT_FILTER_F,PAR_FILTER_FREQ_5},{TEXT_FILTER_RESO,PAR_RESO_5},{TEXT_FILTER_TYPE,PAR_FILTER_TYPE_5},{TEXT_FILTER_DRIVE,PAR_FILTER_DRIVE_5},
{TEXT_FREQ_LFO,PAR_FREQ_LFO5},{TEXT_SYNC_LFO,PAR_SYNC_LFO5},{TEXT_MOD_LFO,PAR_AMOUNT_LFO5},{TEXT_WAVE_LFO,PAR_WAVE_LFO5},
{TEXT_RETRIGGER_LFO,PAR_RETRIGGER_LFO5},{TEXT_OFFSET_LFO,PAR_OFFSET_LFO5},
{TEXT_VOLUME,PAR_VOL5},{TEXT_PAN,PAR_PAN5},{TEXT_SAMPLE_RATE,PAR_VOICE_DECIMATION5},{TEXT_DRIVE,PAR_CYMBAL_DISTORTION},{TEXT_NOTE,PAR_MIDI_NOTE5},
/* Voice 6 (HH) */
{TEXT_COARSE,PAR_COARSE6},{TEXT_FINE,PAR_FINE6},{TEXT_WAVEFORM,PAR_WAVE1_HH},
{TEXT_ATTACK,PAR_VELOA6},{TEXT_DECAY_CLOSED,PAR_VELOD6_CLOSED},{TEXT_DECAY_OPEN,PAR_VELOD6_OPEN},{TEXT_EG_SLOPE,PAR_VOL_SLOPE6},
{TEXT_VEL_DEST,PAR_VEL_DEST_6},{TEXT_VEL_AMT,PAR_VELO_MOD_AMT_6},{TEXT_VEL_MOD_VOL,PAR_VOLUME_MOD_ON_OFF6},
{TEXT_MOD_OSC1_FREQ,PAR_MOD_OSC_F1},{TEXT_MOD_OSC2_FREQ,PAR_MOD_OSC_F2},
{TEXT_MOD_OSC1_GAIN,PAR_MOD_OSC_GAIN1},{TEXT_MOD_OSC2_GAIN,PAR_MOD_OSC_GAIN2},
{TEXT_WAVEFORM,PAR_WAVE2_HH},{TEXT_WAVEFORM,PAR_WAVE3_HH},
{TEXT_TRANSIENT_WAVE,PAR_TRANS6_WAVE},{TEXT_TRANSIENT_VOLUME,PAR_TRANS6_VOL},{TEXT_TRANSIENT_FREQ,PAR_TRANS6_FREQ},
{TEXT_FILTER_F,PAR_FILTER_FREQ_6},{TEXT_FILTER_RESO,PAR_RESO_6},{TEXT_FILTER_TYPE,PAR_FILTER_TYPE_6},{TEXT_FILTER_DRIVE,PAR_FILTER_DRIVE_6},
{TEXT_FREQ_LFO,PAR_FREQ_LFO6},{TEXT_SYNC_LFO,PAR_SYNC_LFO6},{TEXT_MOD_LFO,PAR_AMOUNT_LFO6},{TEXT_WAVE_LFO,PAR_WAVE_LFO6},
{TEXT_RETRIGGER_LFO,PAR_RETRIGGER_LFO6},{TEXT_OFFSET_LFO,PAR_OFFSET_LFO6},
{TEXT_VOLUME,PAR_VOL6},{TEXT_PAN,PAR_PAN6},{TEXT_SAMPLE_RATE,PAR_VOICE_DECIMATION6},{TEXT_DRIVE,PAR_HAT_DISTORTION},{TEXT_NOTE,PAR_MIDI_NOTE6},
};

const ModTargetVoiceOffset modTargetVoiceOffsets[6] = {
    {  2,  35 },
    { 36,  69 },
    { 70, 103 },
    {104, 136 },
    {137, 170 },
    {171, 204 },
};

uint8_t paramToModTarget[END_OF_SOUND_PARAMETERS] = {0};

uint8_t getNumModTargets(void)
{
    return (uint8_t)(sizeof(modTargets)/sizeof(ModTarg));
}

uint8_t voiceFromModTargValue(uint8_t val)
{
    if (modTargetVoiceOffsets[3].start <= val) {
        if (modTargetVoiceOffsets[4].start <= val) {
            if (modTargetVoiceOffsets[5].start <= val) {
                if (modTargetVoiceOffsets[5].end >= val) return 6;
                else return 0;
            } else return 5;
        } else return 4;
    } else {
        if (modTargetVoiceOffsets[0].start <= val) {
            if (modTargetVoiceOffsets[1].start <= val) {
                if (modTargetVoiceOffsets[2].start <= val) return 3;
                else return 2;
            } else return 1;
        } else return 0;
    }
}

void paramToModTargetInit(void)
{
    uint8_t i;
    uint8_t n = getNumModTargets();
    for (i = 0; i < n; i++) {
        uint16_t p = modTargets[i].param;
        if (p < END_OF_SOUND_PARAMETERS)
            paramToModTarget[p] = i;
    }
}

/* Stub implementations — gap-map logic not needed without LFO targeting UI */
uint8_t getModTargetGapIndex(uint8_t modTargetIdx)
{
    (void)modTargetIdx;
    return 0xFF;
}

uint8_t getModTargetIdxFromGapIdx(uint8_t v, uint8_t gapidx)
{
    (void)v; (void)gapidx;
    return 0;
}
