#!/usr/bin/env python3
"""Extract exact C functions, objects, or line ranges for S073 tests.

What:       extracts named source fragments and optionally renames identifiers.
Why:        the golden harness must compile the real old and new source text,
            not a transcription of DSP expressions.
Inputs:     --src, --func/--object/--lines, --rename, --out.
Outputs:    one generated C fragment; missing selectors fail the command.
Accessors:  tools/dsp_test/Makefile.
Affiliates: snapshot.sh and the generated frozen/current fragments.
"""
import argparse
import re
import sys


def _match_block(text, open_idx):
    depth = 0
    for k in range(open_idx, len(text)):
        if text[k] == '{':
            depth += 1
        elif text[k] == '}':
            depth -= 1
            if depth == 0:
                return k
    return -1


def find_function(text, name):
    head = re.compile(r'^[^\n;#]*\b' + re.escape(name) + r'\s*\(', re.M)
    for m in head.finditer(text):
        i, depth = m.end() - 1, 0
        while i < len(text):
            if text[i] == '(':
                depth += 1
            elif text[i] == ')':
                depth -= 1
                if depth == 0:
                    break
            i += 1
        j = i + 1
        while j < len(text) and text[j] in ' \t\r\n':
            j += 1
        if j < len(text) and text[j] == '{':
            end = _match_block(text, j)
            if end > 0:
                return text[m.start():end + 1]
    return None


def find_object(text, name):
    m = re.search(r'^[^\n;#]*\b' + re.escape(name) + r'\s*\[[^\]]*\]\s*=\s*\{',
                  text, re.M)
    if not m:
        return None
    end = _match_block(text, m.end() - 1)
    semi = text.index(';', end)
    return text[m.start():semi + 1]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--src', required=True)
    ap.add_argument('--func', action='append', default=[])
    ap.add_argument('--object', action='append', default=[])
    ap.add_argument('--lines')
    ap.add_argument('--rename', action='append', default=[])
    ap.add_argument('--out', required=True)
    a = ap.parse_args()
    with open(a.src) as source:
        text = source.read()
    parts = []
    if a.lines:
        lo, hi = (int(v) for v in a.lines.split('-', 1))
        parts.append('\n'.join(text.splitlines()[lo - 1:hi]))
    for name in a.object:
        got = find_object(text, name)
        if got is None:
            sys.exit(f'extract.py: object {name} not found in {a.src}')
        parts.append(got)
    for name in a.func:
        got = find_function(text, name)
        if got is None:
            sys.exit(f'extract.py: function {name} not found in {a.src}')
        parts.append(got)
    out = '\n\n'.join(parts) + '\n'
    for pair in a.rename:
        old, new = pair.split('=', 1)
        out = re.sub(r'\b' + re.escape(old) + r'\b', new, out)
    with open(a.out, 'w') as generated:
        generated.write(f'/* generated by extract.py from {a.src} */\n' + out)


if __name__ == '__main__':
    main()
